image: node:latest

services:
  - mysql:latest

variables:
  # Configure mysql environment variables (https://hub.docker.com/_/mysql/)
  MYSQL_DATABASE: "c37_cablink"
  MYSQL_ROOT_PASSWORD: "wlindl!"

cache:
  paths:
    - node_modules/

test_async:
  script:
    - npm install

test_db:
  image: mysql
  script:
  - echo "SELECT 'OK';" | mysql --user=c37_cablink --password="$MYSQL_ROOT_PASSWORD" --host=dragon "$MYSQL_DATABASE"